project 'Quiztory.xcodeproj'

# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Quiztory' do

  use_frameworks!

  pod 'Alamofire'
  pod 'SwiftyJSON'

end
